### ISSUE TITLE
Update code to include accountant/calculator

### ISSUE THREAD

**Issue by bellalaf-unimelb** [bellalaf-unimelb/T4_automail_P1#2]

**Comment by Z4m4niB** [comment]
1. MailItem needs 2 new attributes: lookupCount and movementCount (both initiated to 0)
2. Robot needs to update above attributes for the appropriate MailItem in the appropriate times
3. For 2, MailItem needs 2 new methods: countLookup and countMovement (which just increment their respective attribute)

**Comment by Z4m4niB** [comment]
Also I don't remember what happens to a MailItem if delivery fails, but if it goes back into the MailPool, then its lookupCount and movementCount should be reset to 0 (because they would already have been logged by that point)
