### ISSUE TITLE
goddamn sneaky DS_Codes

### ISSUE THREAD

**Issue by Z4m4niB** [bellalaf-unimelb/T4_automail_P1#5]
every fucking time

**Comment by Z4m4niB** [comment]
apparently just putting .DS_Store in the root directory's .gitignore should recursively ignore any file called .DS_Store so idk why/whether it's not working.

**Comment by bellalaf-unimelb** [comment]
Mine didn't add this time - are you still having this issue?

**Comment by Z4m4niB** [comment]
When you have .DS_Store files in your repository before you git init then adding .DS_Store in .gitignore won't do anything because they are already in the repo. I fixed it by removing the .DS_Store files individually. The .gitignore works fine.
