### ISSUE TITLE
Default configuration for Calculator

### ISSUE THREAD

**Issue by Z4m4niB** [bellalaf-unimelb/T4_automail_P1#6]
You might say this issue has too many labels, but I say I like the pretty colours.

So the thing is, Claire and I added some functionality to Simulation which would configure Calculator, either from the file or from default values. And it's pretty neat.

But, we also still want Auto-Mail to function outside of Simulation, right? That includes Calculator.

So I see a few options here:

1. Have the defaults in Calculator AND Simulation.
- Downside: duplicate code

2. Have the defaults in Calculator only, Simulation configures only when config file has something in it.
- Downside: checking if the config file has something in it would make for some ugly code in Simulation.

3. Have the defaults in Simulation only, Calculator throws errors if it's used before it's configured.
- Force users outside of Simulation to make sure they configure Calculator with their own defaults and/or config file.
- Downside: Need to make a bunch of custom errors and throw them, which is ugly imo. Also it feels like a whiny thing to do.

4. Have Calculator default everything to zero. Simulation can keep the real defaults.
- No errors from Calculator when not configured, but also no duplicate code.
- Downside: relies on documentation to inform users outside of Simulation they need to configure Calculator. Users will be confused when all the costs are zero.

To me, number 4 makes the most sense. It's also very easy to implement. So that's what I'm doing. If you disagree, choose an option (or come up with a new one) and I will take care of it.

**Comment by Z4m4niB** [comment]
Also, are we happy with isChargeDisplayEnabled and enableChargeDisplay() in Accountant? Or do we want to add getChargeDisplay() to Simulation?

**Comment by bellalaf-unimelb** [comment]
4 is fine by me. 
I like how it is - chargeDisplay is in Accountant gets used in there for the stats and its a part of accountant.
